version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin123!
      MYSQL_DATABASE: test
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network

  app:
    container_name: node.js
    image: nodejs-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    depends_on:
      - db
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mysql_data:
